version: '3'

services:
  db_test:
    container_name: test_pechenkin_postgres
    image: postgres:latest
    env_file:
      - ./.env
    restart: always
    ports:
      - "5432:5432"
    networks:
      - ylab_project_1


  fastapi_test:
    container_name: fastapi_pechenkin_test
    build:
      context: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - ylab_project_1
    restart: always
    depends_on:
      - db_test


networks:
  ylab_project_1:
    driver: bridge
