version: '3'

services:
  db:
    container_name: test_pechenkin_postgres
    image: postgres:latest
    env_file:
      - ./.env
    restart: always
    ports:
      - "5432:5432"
    networks:
      - ylab_project_2


  fastapi:
    container_name: fastapi_pechenkin_test
    build:
      context: .
    command: uvicorn application.main:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - ylab_project_2
    restart: always
    depends_on:
      - db


networks:
  ylab_project_2:
    driver: bridge
